#ifndef DC_INDICATOR_TYPE_H
#define DC_INDICATOR_TYPE_H

typedef enum
{
  DC_INDICATOR_STATE_OFF = 0,
  DC_INDICATOR_STATE_BOOTING,
  DC_INDICATOR_STATE_IDLE,
  DC_INDICATOR_STATE_OK,
  DC_INDICATOR_STATE_WARNING,
  DC_INDICATOR_STATE_ERROR,
  DC_INDICATOR_STATE_FATAL,
  DC_INDICATOR_STATE_CONNECTING,
} dc_indicator_state_id_t;

#endif